name: Fince Project CI/CD

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Install Application Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Install Serve (if not installed)
        run: sudo npm install -g serve

      - name: PM2 Delete previous process
        run: pm2 delete fince-frontend || true

      - name: Start production build with PM2
        run: pm2 start "npm run serve" --name fince-frontend 

      - name: PM2 Save Process List
        run: pm2 save

      - name: Show PM2 Status
        run: pm2 status
